version: '3.8'

services:
  mongo:
    build: ./mongo
    container_name: mongo-datasetpolicies
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  app:
    build: .
    container_name: encryption-api
    ports:
      - "8000:8000"
    environment:
      # MinIO Configuration
      - MINIO_ENDPOINT=minio-api.vessel-ai.eu
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      # Set to True for HTTPS, False for HTTP
      - MINIO_SECURE=True
      - RETENTION_SECONDS=30
      - RETENTION_PREFIX=weather

      # Bucket Configuration
      - SOURCE_BUCKET=demo-data
      - DESTINATION_BUCKET=encrypted-files

      # App Settings
      - POLL_INTERVAL=5

      # MongoDB Configuration
      - MONGO_URI=mongodb://root:rootpassword@mongo:27017
      - MONGO_DB=datasetPolicies
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
